//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieHubDatabaseEntities1 : DbContext
    {
        public MovieHubDatabaseEntities1()
            : base("name=MovieHubDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cinema> Cinemas { get; set; }
        public virtual DbSet<MovieData> MovieDatas { get; set; }
        public virtual DbSet<Screen> Screens { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
