//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class MovieData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieData()
        {
            this.Seats = new HashSet<Seat>();
        }
    
        public int M_Id { get; set; }
        public string M_Name { get; set; }
        public string M_Category { get; set; }
        public int M_Price { get; set; }
        public System.DateTime M_StartDate { get; set; }
        public System.DateTime M_EndDate { get; set; }
        public string M_Status { get; set; }
        public string M_Description { get; set; }
        public string M_img { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        
        public string M_Banner { get; set; }
        public HttpPostedFileBase BannerFile { get; set; }
        public string M_Duration { get; set; }
        public System.TimeSpan M_ShowtimeStart { get; set; }
        public System.TimeSpan M_ShowtimeEnd { get; set; }
        public int M_ScreenId { get; set; }
    
        public virtual Screen Screen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
