//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int Se_Id { get; set; }
        public string Se_Number { get; set; }
        public string Se_UserName { get; set; }
        public int Se_Movie_id { get; set; }
        public int Se_User_id { get; set; }
    
        public virtual MovieData MovieData { get; set; }
        public virtual User User { get; set; }
    }
}
